name: Generate Version

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  generate_version_job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: gen-semver
      uses: ./.github/actions/generate-version-action
      id: generate-version
      with:
        ci-repository-url: 'https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git'
    
    - name: Output Version
      run: echo "${{ steps.gen-semver.outputs.version }}"
